# Generated by Django 3.0.3 on 2020-03-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_noticia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data',
            field=models.DateField(blank=True, max_length=128, null=True, verbose_name='data'),
        ),
    ]
