# Generated by Django 3.0.3 on 2020-03-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='tags',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='tag'),
        ),
    ]
